#' @return a nested list giving results of the simulation with the following structure:
#' * **hypothesis.testing**       - description
#'   - **rr**                     - description
#'   - **fw.fpr**                 - description
#'   - **nerr**                   - description
#'   - **fut**                    - description
#' * **sample.size**              - description
#'   - **basket.ave**             - description
#'   - **basket.med**             - description
#'   - **basket.min**             - description
#'   - **basket.max**             - description
#'   - **overall.ave**            - description
#' * **point.estimation**         - description
#'   - **PM.ave**                 - description
#'   - **SP.ave**                 - description
#'   - **PP.ave**                 - description
#'   - **bias**                   - description
#'   - **mse**                    - description
#' * **early.stopping**           - description
#'   - **interm.stop.prob**       - description
#'   - **baskets.continuing.ave** - description