# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Compute number of models
#' 
#' Given a basket size and maximal number of distinct
#' response rates, compute the number of possible models
#' 
#' @param K positive integer giving number of baskets
#' @param P positive integer giving maximal number of distinct rates
#' 
#' @return integer giving number of possible models
#' @noRd
numModels_cpp <- function(K, P) {
    .Call('_bmabasket_numModels_cpp', PACKAGE = 'bmabasket', K, P)
}

#' Model matrix of data given model
#' 
#' Get the (collapsed) model data specified by a particular partition (model)
#' 
#' @param datMat     matrix of \code{(y, n-y)} data
#' @param partition  vector of indices giving how to partition the data
#' 
#' @keywords internal
#' @noRd
modelMatrix <- function(datMat, partition) {
    .Call('_bmabasket_modelMatrix', PACKAGE = 'bmabasket', datMat, partition)
}

#' Model matrix of data given model
#' 
#' Get the (collapsed) model data specified by a particular partition (model)
#' 
#' @param datMat     matrix of \code{(y, n-y)} data
#' @param partition  vector of indices giving how to partition the data
#' 
#' @keywords internal
#' @noRd
modelMatrix2 <- function(datMat, partition) {
    .Call('_bmabasket_modelMatrix2', PACKAGE = 'bmabasket', datMat, partition)
}

#' Log posterior survival probability
#' 
#' Given a vector that gives a partition, computes the posterior probability 
#' that the basket proportion is larger than some specified value
#' 
#' @param pi0        vector whose elements are between 0 and 1 giving threshold for the hypothesis test. If a scalar is provided, assumes same threshold for each basket.
#' @param datMat     matrix of data. The first column gives the number of "successes" and second gives number of "failures" for each basket.
#' @param partition  vector giving a partition for a particular model
#' @param a0         beta prior shape parameter
#' @param b0         beta prior shape parameter
logPostSurvProb <- function(pi0, datMat, partition, a0, b0, lbeta_a0b0) {
    .Call('_bmabasket_logPostSurvProb', PACKAGE = 'bmabasket', pi0, datMat, partition, a0, b0, lbeta_a0b0)
}

#' Bayesian model averaging
#'
#' Computes posterior model probabilities and Bayes model averaged survival function \math{P(\pi_k > pi0 | D)}
#'
#' @param pi0            vector whose elements are between 0 and 1 giving cutoffs for effect size for each basket
#' @param datMat         matrix of data \code{(y, n - y)}
#' @param partitionMat   martrix giving how to partition the data for each model
#' @param mu0            scalar giving prior mean for beta prior
#' @param phi0           scalar giving prior dispersion for beta prior
#' @param logModelPriors vector of length P giving the normalized priors for each model
#'
#' @return a vector giving the Bayesian model averaged posterior probability
#' @keywords internal
#' @noRd
bma_cpp <- function(pi0, datMat, partitionMat, mu0, phi0, logModelPriors) {
    .Call('_bmabasket_bma_cpp', PACKAGE = 'bmabasket', pi0, datMat, partitionMat, mu0, phi0, logModelPriors)
}

