# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Model matrix of data given model
#' 
#' Get the (collapsed) model data specified by a particular partition (model)
#' 
#' @param datMat     matrix of \code{(y, n-y)} data
#' @param partition  vector of indices giving how to partition the data
#' 
#' @keywords internal
#' @noRd
NULL

#' Compute number of models
#' 
#' Given a basket size and maximal number of distinct
#' response rates, compute the number of possible models
#' 
#' @param K positive integer giving number of baskets
#' @param P positive integer giving maximal number of distinct rates
#' 
#' @return integer giving number of possible models
#' @noRd
numModels_cpp <- function(K, P) {
    .Call('_bmabasket_numModels_cpp', PACKAGE = 'bmabasket', K, P)
}

#' Bayesian model averaging
#' 
#' Computes posterior model probabilities and Bayes model averaged survival function \math{P(\pi_k > x | D)}
#' 
#' @param x              scalar between 0 and 1 giving cutoff for effect size
#' @param datMat         matrix of data \code{(y, n - y)}
#' @param partitionMat   martrix giving how to partition the data for each model
#' @param mu0            scalar giving prior mean for beta prior
#' @param phi0           scalar giving prior dispersion for beta prior
#' @param logchoose      scalar giving \code{sum(lchoose(n, y))}
#' @param P              integer scalar giving number of models
#' @param logModelPriors vector of length P giving the normalized priors for each model
#' 
#' @return a list giving \code{[[posteriorSurvivalFunction], [posteriorModelProbs]]}
#' @keywords internal
#' @noRd
bma_cpp <- function(x, datMat, partitionMat, mu0, phi0, logchoose, logModelPriors) {
    .Call('_bmabasket_bma_cpp', PACKAGE = 'bmabasket', x, datMat, partitionMat, mu0, phi0, logchoose, logModelPriors)
}

